"""Game configuration constants"""

# Upgrade costs and multipliers
UPGRADE_CAPACITY_MULTIPLIER = 25
UPGRADE_SPEED_BASE = 100
UPGRADE_SPEED_FACTOR = 30
UPGRADE_SPEED_DECREASE = 0.2
UPGRADE_SPEED_MIN_COST = 50

# Initial game values
INITIAL_ITEM_CAPACITY = 2
INITIAL_MINING_TIME = 3
INITIAL_MONEY = 0
INITIAL_INVENTORY = []

# Mining settings
ORE_POOL_SIZE = 5
ITEM_DROP_RANGE = (1, 2)
MINING_ANIMATION_FRAMES = 3

# UI settings
SLOWPRINT_DELAY = 0.04
CHOICE_TIMEOUT = 1
BASIC_EVENT_PRINT_DELAY = 0.05
CONSQ_EVENT_PRINT_DELAY = 0.1

# Event
BASIC_EVENT_CHANCE = 0.2  # 20%
DECREASE_SPEED_EVENT_AREA = (1, 5)  # 10% - 50%